insert into A_CATEGORIA (NOMBRECATEGORIA) values ('Automotive');
insert into A_CATEGORIA (NOMBRECATEGORIA) values ('Baby');
insert into A_CATEGORIA (NOMBRECATEGORIA) values ('Beauty');
insert into A_CATEGORIA (NOMBRECATEGORIA) values ('Books');
insert into A_CATEGORIA (NOMBRECATEGORIA) values ('Cars');
insert into A_CATEGORIA (NOMBRECATEGORIA) values ('Clothing');
insert into A_CATEGORIA (NOMBRECATEGORIA) values ('Computers');
insert into A_CATEGORIA (NOMBRECATEGORIA) values ('Conservatives');
insert into A_CATEGORIA (NOMBRECATEGORIA) values ('Disinfectant');
insert into A_CATEGORIA (NOMBRECATEGORIA) values ('Decoration');
insert into A_CATEGORIA (NOMBRECATEGORIA) values ('Drinks');
insert into A_CATEGORIA (NOMBRECATEGORIA) values ('Electronics');
insert into A_CATEGORIA (NOMBRECATEGORIA) values ('Frozen');
insert into A_CATEGORIA (NOMBRECATEGORIA) values ('Fruts');
insert into A_CATEGORIA (NOMBRECATEGORIA) values ('Games');
insert into A_CATEGORIA (NOMBRECATEGORIA) values ('Garden');
insert into A_CATEGORIA (NOMBRECATEGORIA) values ('Health');
insert into A_CATEGORIA (NOMBRECATEGORIA) values ('Home');
insert into A_CATEGORIA (NOMBRECATEGORIA) values ('Industrial');
insert into A_CATEGORIA (NOMBRECATEGORIA) values ('Jewelery');
insert into A_CATEGORIA (NOMBRECATEGORIA) values ('Kids');
insert into A_CATEGORIA (NOMBRECATEGORIA) values ('Meat');
insert into A_CATEGORIA (NOMBRECATEGORIA) values ('Movies');
insert into A_CATEGORIA (NOMBRECATEGORIA) values ('Music');
insert into A_CATEGORIA (NOMBRECATEGORIA) values ('Outdoors');
insert into A_CATEGORIA (NOMBRECATEGORIA) values ('Pesticides');
insert into A_CATEGORIA (NOMBRECATEGORIA) values ('Shoes');
insert into A_CATEGORIA (NOMBRECATEGORIA) values ('Sports');
insert into A_CATEGORIA (NOMBRECATEGORIA) values ('Sweets');
insert into A_CATEGORIA (NOMBRECATEGORIA) values ('Tools');
insert into A_CATEGORIA (NOMBRECATEGORIA) values ('Toys');
insert into A_CATEGORIA (NOMBRECATEGORIA) values ('Veterinary hygiene');
insert into A_CATEGORIA (NOMBRECATEGORIA) values ('Vegetables');
insert into A_CATEGORIA (NOMBRECATEGORIA) values ('Water');

select * from a_categoria;