--- Sentencias SQL para la creación del esquema de superAndes
--- Las tablas tienen prefijo A_ para facilitar su acceso desde SQL Developer
-- USO
-- Copie el contenido de este archivo en una pestaña SQL de SQL Developer
-- Ejecútelo como un script - Utilice el botón correspondiente de la pestaña
-- utilizada
-- Creación del secuenciador
CREATE sequence superandes_sequence;

  -- Creaación de la tabla PRODUCTO y especificación de sus restricciones
  CREATE
    TABLE A_PRODUCTO
    (
      NOMBRE_PRODUCTO   VARCHAR(255) NOT NULL,
      MARCA             VARCHAR(255) NOT NULL,
      PRECIO_UNITARIO   NUMBER NOT NULL,
      PRESENTACION      VARCHAR(50) NOT NULL,
      PRECIO_UNI_MEDIDA NUMBER NOT NULL,
      CANT_PRESENTACION NUMBER NOT NULL,
      UNIDAD_MEDIDA     VARCHAR(50) NOT NULL,
      VOLUMEN_PRODUCTO  VARCHAR(255) NOT NULL,
      PESO_PRODUCTO     VARCHAR(255) NOT NULL,
      COD_BARRAS        VARCHAR(255) NOT NULL,
      CALIDAD           VARCHAR(255),
      FECHA_VENCIMIENTO DATE,
      CONSTRAINT A_PRODUCTO_PK PRIMARY KEY(COD_BARRAS)
    );
  ALTER TABLE A_PRODUCTO 
    ADD CONSTRAINT CK_PRODUCTO_PU 
    CHECK (PRECIO_UNITARIO > 0) 
  ENABLE;
  ALTER TABLE A_PRODUCTO 
    ADD CONSTRAINT CK_PRODUCTO_PUM 
    CHECK (PRECIO_UNI_MEDIDA > 0)
  ENABLE;
  ALTER TABLE A_PRODUCTO 
    ADD CONSTRAINT CK_PRODUCTO_CP 
    CHECK (CANT_PRESENTACION > 0) 
  ENABLE;

  -- Creación de la tabla CATEGORIA y especificación de sus restricciones
 CREATE
  TABLE A_CATEGORIA
  (
    NOMBRE_CATEGORIA VARCHAR(100),
    CONSTRAINT A_CATEGORIA_PK PRIMARY KEY(NOMBRE_CATEGORIA)
  );
    
  -- Creación de la tabla SUCURSAL y especificación de sus restricciones
  CREATE
    TABLE A_SUCURSAL
    (
      TAMANIO NUMBER NOT NULL,
      DIRECCION_SUCURSAL VARCHAR(255),
      CIUDAD VARCHAR(255),
      NOMBRE_SUCURSAL VARCHAR(255) NOT NULL,
      CONSTRAINT A_SUCURSAL_PK PRIMARY KEY(DIRECCION_SUCURSAL, CIUDAD)
    );
    
  -- Creación de la tabla CLIENTE y especificación de sus restricciones    
  CREATE
    TABLE A_CLIENTE
    (
      NOMBRE_CONSUMIDOR VARCHAR(255) NOT NULL,
      CORREO VARCHAR(255),
      PUNTOS NUMBER,
      CONSTRAINT A_CLIENTE_PK PRIMARY KEY(CORREO)
    );
  ALTER TABLE A_CLIENTE
    ADD CONSTRAINT CK_CLIENTE_PT
    CHECK(PUNTOS >= 0)
  ENABLE;
  
  
  -- Creación de la tabla PERSONA NATURAL y especificación de sus restricciones 
  CREATE
    TABLE A_PERSONA_NATURAL
    (
      CORREO VARCHAR(255),
      DOCUMENTO VARCHAR(255) NOT NULL,
      CONSTRAINT A_PERSONA_NATURAL_PK PRIMARY KEY (CORREO)
    );
  ALTER TABLE A_PERSONA_NATURAL
    ADD CONSTRAINT FK_PN_CLIENTE
      FOREIGN KEY (CORREO)
      REFERENCES A_CLIENTE(CORREO)
  ENABLE;

  -- Creación de la tabla EMPRESA y especificación de sus restricciones
  CREATE
    TABLE A_EMPRESA
    (
      CORREO VARCHAR(255),
      NIT_EMPRESA NUMBER,
      DIRECCION VARCHAR(255) NOT NULL,
      CONSTRAINT A_EMPRESA_PK PRIMARY KEY (CORREO)
    );
  ALTER TABLE A_EMPRESA
    ADD CONSTRAINT FK_EM_CLIENTE
      FOREIGN KEY (CORREO)
      REFERENCES A_CLIENTE(CORREO)
  ENABLE;
  
  -- Creación de la tabla PROVEEDOR y especificación de sus restricciones
  CREATE
    TABLE A_PROVEEDOR
    (
      NIT_PROVEEDOR NUMBER,
      NOMBRE_PROVEEDOR VARCHAR(255) NOT NULL,
      CALIFICACION_PROVEEDOR VARCHAR(255),
      CONSTRAINT A_PROVEEDOR_PK PRIMARY KEY(NIT_PROVEEDOR)
    );
  ALTER TABLE A_PROVEEDOR
    ADD CONSTRAINT CK_PROVEEDOR_CP
    CHECK (CALIFICACION_PROVEEDOR > 0)
  ENABLE;
  
  -- Creación de la tabla TIPO PRODUCTO y especificación de sus restricciones
  CREATE
    TABLE A_TIPO_PRODUCTO
    (
      NOMBRE_TIPO VARCHAR(255),
      NOMBRE_CATEGORIA VARCHAR(255),
      CONSTRAINT A_TIPO_PRODUCTO_PK PRIMARY KEY(NOMBRE_TIPO)
    );
  ALTER TABLE A_TIPO_PRODUCTO
    ADD CONSTRAINT FK_TP_CATEGORIA
      FOREIGN KEY (NOMBRE_CATEGORIA)
      REFERENCES A_CATEGORIA (NOMBRE_CATEGORIA)
  ENABLE;
  
  -- Creación de la tabla FACTURA y especificaión de sus restricciones
  CREATE
    TABLE A_FACTURA
    (
      ID_FACTURA NUMBER,
      FECHA DATE NOT NULL,
      COSTO_TOTAL NUMBER NOT NULL,
      CONSTRAINT A_FACTURA_PK PRIMARY KEY(ID_FACTURA)
    );
  ALTER TABLE A_FACTURA
    ADD CONSTRAINT CK_A_FACTURA
    CHECK (COSTO_TOTAL > 0)
  ENABLE;
  
  -- Creación de la tabla PROVEEN y especificación de sus restricciones
  CREATE
    TABLE A_PROVEEN
    (
      NIT_PROVEEDOR NUMBER,
      COD_BARRAS VARCHAR(255),
      CONSTRAINT A_PROVEEN_PK PRIMARY KEY(NIT_PROVEEDOR, COD_BARRAS)
    );
  ALTER TABLE A_PROVEEN
    ADD CONSTRAINT FK_NP_PROVEEN
      FOREIGN KEY (NIT_PROVEEDOR)
      REFERENCES A_PROVEEDOR (NIT_PROVEEDOR)
  ENABLE;
  ALTER TABLE A_PROVEEN
    ADD CONSTRAINT FK_CB_PROVEEN
      FOREIGN KEY (COD_BARRAS)
      REFERENCES A_PRODUCTO (COD_BARRAS)
  ENABLE;
  
  -- Creación de la tabla HISTORIAL COMPRAS y especificaión de sus restricciones
  CREATE
    TABLE A_HISTORIAL_COMPRAS
  (
    CORREO_CLIENTE VARCHAR(255),
    ID_FACTURA NUMBER,
    CONSTRAINT A_HISTORIAL_COMPRAS_PK PRIMARY KEY(CORREO_CLIENTE, ID_FACTURA)
  );
  ALTER TABLE A_HISTORIAL_COMPRAS
    ADD CONSTRAINT FK_CC_HISTORIAL_COMPRAS
      FOREIGN KEY (CORREO_CLIENTE)
      REFERENCES A_CLIENTE (CORREO)
  ENABLE;
  ALTER TABLE A_HISTORIAL_COMPRAS
    ADD CONSTRAINT FK_IF_HISTORIAL_COMPRAS
      FOREIGN KEY (ID_FACTURA)
      REFERENCES A_FACTURA (ID_FACTURA)
  ENABLE;
  
  -- Creacion de la tabla ESTANTE y especificacion de sus restricciones
  CREATE
  TABLE A_ESTANTE
  (
       TIPO_ESTANTE VARCHAR(255) NOT NULL,
       VOLUMEN_ESTANTE NUMBER NOT NULL,
       ID_ESTANTE NUMBER,
       PESO_ESTANTE NUMBER NOT NULL,
       NIVEL_ABASTECIMIENTO NUMBER NOT NULL,
       DIRECCION_SUCURSAL VARCHAR(255),
       CIUDAD VARCHAR(255),
       CONSTRAINT A_ESTANTE_PK PRIMARY KEY (ID_ESTANTE)
  );
  ALTER TABLE A_ESTANTE
    ADD CONSTRAINT FK_DS_ESTANTE
      FOREIGN KEY (DIRECCION_SUCURSAL, CIUDAD)
      REFERENCES A_SUCURSAL (DIRECCION_SUCURSAL, CIUDAD)
  ENABLE;
  ALTER TABLE A_ESTANTE
   ADD CONSTRAINT CK_ESTANTE_VE
   CHECK (VOLUMEN_ESTANTE > 0) 
  ENABLE;
  ALTER TABLE A_ESTANTE
   ADD CONSTRAINT CK_ESTANTE_PE
   CHECK (PESO_ESTANTE > 0) 
  ENABLE;
 
 -- Creación de la tabla PROMOCIÓN y especificación de sus restricciones
 CREATE
    TABLE A_PROMOCION
    (
        FECHA_INCIAL DATE NOT NULL,
        FECHA_FINAL DATE,
        DESCRIPCION VARCHAR(255) NOT NULL,
        ID_PROMOCION NUMBER,
        UNIDADES_DISPONIBLES NUMBER NOT NULL,
        UNIDADES_VENDIDAS NUMBER,
        CODIGO_BARRAS VARCHAR(255) NOT NULL,
        ESTADO VARCHAR(255) NOT NULL,
        CONSTRAINT A_PROMOCION_PK PRIMARY KEY (ID_PROMOCION)
    );
 ALTER TABLE A_PROMOCION
    ADD CONSTRAINT FK_CD_PROMOCION
    FOREIGN KEY (CODIGO_BARRAS)
    REFERENCES A_PRODUCTO (COD_BARRAS)
 ENABLE;
 ALTER TABLE A_PROMOCION
    ADD CONSTRAINT CK_UD_PROMOCION
    CHECK (UNIDADES_DISPONIBLES >= 0)
 ENABLE;
  ALTER TABLE A_PROMOCION
    ADD CONSTRAINT CK_UV_PROMOCION
    CHECK (UNIDADES_VENDIDAS >= 0)
 ENABLE;
  ALTER TABLE A_PROMOCION
    ADD CONSTRAINT CK_E_PROMOCION
    CHECK (ESTADO IN ('VIGENTE', 'FINALIZADA'))
 ENABLE;    

 -- Creación de la tabla PROMOCIONES y especificación de sus restricciones
 CREATE
    TABLE A_PROMOCIONES
    (
        ID_PROMOCION NUMBER,
        DIRECCION_SUCURSAL VARCHAR(255),
        CIUDAD VARCHAR(255),
        CONSTRAINT A_PROMOCIONES_PK PRIMARY KEY (ID_PROMOCION, DIRECCION_SUCURSAL, CIUDAD)
    );
 ALTER TABLE A_PROMOCIONES
    ADD CONSTRAINT FK_S_PROMOCIONES
    FOREIGN KEY (DIRECCION_SUCURSAL, CIUDAD)
    REFERENCES A_SUCURSAL (DIRECCION_SUCURSAL, CIUDAD)
 ENABLE;
 ALTER TABLE A_PROMOCIONES
    ADD CONSTRAINT FK_IP_PROMOCIONES
    FOREIGN KEY (ID_PROMOCION)
    REFERENCES A_PROMOCION (ID_PROMOCION)
 ENABLE;
    
  -- Creacion de la tabla PEDIDO PRODUCTO y especificacion de sus restricciones
  CREATE
  TABLE A_PEDIDO_PRODUCTO
  (
      CODIGO_BARRAS VARCHAR(255),
      ID_PEDIDO NUMBER,
      CANTIDAD_PRODUCTO NUMBER,
      PRECIO_PRODUCTO NUMBER,
      CONSTRAINT A_PEDIDO_PRODUCTO_PK PRIMARY KEY (ID_PEDIDO)
  );
  ALTER TABLE A_PEDIDO_PRODUCTO
    ADD CONSTRAINT FK_CB_PEDIDO_PRODUCTO
    FOREIGN KEY (CODIGO_BARRAS)
    REFERENCES A_PRODUCTO (COD_BARRAS)
  ENABLE;
  ALTER TABLE A_PEDIDO_PRODUCTO
    ADD CONSTRAINT CK_PEDIDO_PRODUCTO_CP
    CHECK (CANTIDAD_PRODUCTO > 0) 
  ENABLE;
  ALTER TABLE A_PEDIDO_PRODUCTO
    ADD CONSTRAINT CK_PEDIDO_PRODUCTO_PP
    CHECK (PRECIO_PRODUCTO > 0) 
  ENABLE;
-- Creacion de la tabla BODEGA y especificacion de sus restricciones
 CREATE
  TABLE A_BODEGA
  (
      TIPO_BODEGA VARCHAR(255)NOT NULL,
      VOLUMEN_BODEGA NUMBER NOT NULL,
      PESO_BODEGA NUMBER NOT NULL,
      DIRECCION_BODEGA VARCHAR(255),
      DIRECCION_SUCURSAL VARCHAR(255),
      CIUDAD VARCHAR(255),
      CONSTRAINT A_BODEGA_PK PRIMARY KEY(DIRECCION_BODEGA, DIRECCION_SUCURSAL, CIUDAD)
  );
  ALTER TABLE A_BODEGA
    ADD CONSTRAINT FK_DS_BODEGA
    FOREIGN KEY (DIRECCION_SUCURSAL, CIUDAD)
    REFERENCES A_SUCURSAL (DIRECCION_SUCURSAL, CIUDAD)
  ENABLE;
  
-- Creacion de la tabla COMPRADOS y especificacion de sus restricciones
CREATE
  TABLE A_COMPRADOS
  (
      CODIGO_BARRAS VARCHAR(255),
      ID_FACTURA NUMBER,
      CANTIDAD NUMBER NOT NULL,
      PRECIO_TOTAL NUMBER NOT NULL,
      CONSTRAINT A_COMPRADOS_PK PRIMARY KEY(CODIGO_BARRAS, ID_FACTURA)
  );  
  ALTER TABLE A_COMPRADOS
    ADD CONSTRAINT FK_CB_COMPRADOS
    FOREIGN KEY (CODIGO_BARRAS)
    REFERENCES A_PRODUCTO (COD_BARRAS)
  ENABLE;
  ALTER TABLE A_COMPRADOS
    ADD CONSTRAINT FK_IDF_COMPRADOS
    FOREIGN KEY (ID_FACTURA)
    REFERENCES A_FACTURA (ID_FACTURA)
  ENABLE;
  ALTER TABLE A_COMPRADOS
    ADD CONSTRAINT CK_COMPRADOS_C
    CHECK (CANTIDAD > 0) 
  ENABLE;
  ALTER TABLE A_COMPRADOS
    ADD CONSTRAINT CK_COMPRADOS_PT
    CHECK (PRECIO_TOTAL > 0) 
  ENABLE;
-- Creacion de la tabla CANTIDAD_EN_BODEGA y especificacion de sus restricciones
CREATE
  TABLE A_CANTIDAD_EN_BODEGA
  (
      CODIGO_BARRAS VARCHAR(255),
      DIRECCION_BODEGA VARCHAR(255),
      DIRECCION_SUCURSAL VARCHAR(255),
      CIUDAD VARCHAR(255),
      CANTIDAD_ACTUAL NUMBER NOT NULL,
      CANTIDAD_MINIMA NUMBER NOT NULL,
      CONSTRAINT A_CANTIDAD_EN_BODEGA_PK PRIMARY KEY(CODIGO_BARRAS, DIRECCION_BODEGA, DIRECCION_SUCURSAL, CIUDAD)
  );
  ALTER TABLE A_CANTIDAD_EN_BODEGA
    ADD CONSTRAINT FK_CB_CANTIDAD_EN_BODEGA
    FOREIGN KEY (CODIGO_BARRAS)
    REFERENCES A_PRODUCTO (COD_BARRAS)
  ENABLE;
  ALTER TABLE A_CANTIDAD_EN_BODEGA
    ADD CONSTRAINT FK_DB_CANTIDAD_EN_BODEGA
    FOREIGN KEY (DIRECCION_BODEGA, DIRECCION_SUCURSAL, CIUDAD)
    REFERENCES A_BODEGA (DIRECCION_BODEGA, DIRECCION_SUCURSAL, CIUDAD)
  ENABLE;
  ALTER TABLE A_CANTIDAD_EN_BODEGA
    ADD CONSTRAINT CK_CANTIDAD_EN_BODEGA_CA
    CHECK (CANTIDAD_ACTUAL > 0) 
  ENABLE;
  ALTER TABLE A_CANTIDAD_EN_BODEGA
    ADD CONSTRAINT CK_CANTIDAD_EN_BODEGA_CM
    CHECK (CANTIDAD_MINIMA > 0) 
  ENABLE;
  
  -- Creación de la tabla CANTIDAD EN ESTANTES y especificación de sus restricciones
  CREATE
    TABLE A_CANTIDAD_EN_ESTANTES
    (
    CODIGO_BARRAS VARCHAR(255),
    ID_ESTANTE NUMBER,
    CANTIDAD_ACTUAL NUMBER NOT NULL,
    CANTIDAD_MINIMA NUMBER NOT NULL,
    CONSTRAINT A_CANTIDAD_EN_ESTANTES_PK PRIMARY KEY (CODIGO_BARRAS, ID_ESTANTE)
    );
 ALTER TABLE A_CANTIDAD_EN_ESTANTES
    ADD CONSTRAINT FK_CD_PRODUCTO
      FOREIGN KEY (CODIGO_BARRAS)
      REFERENCES A_PRODUCTO(COD_BARRAS)
  ENABLE;
 ALTER TABLE A_CANTIDAD_EN_ESTANTES
    ADD CONSTRAINT FK_IE_PRODUCTO
      FOREIGN KEY (ID_ESTANTE)
      REFERENCES A_ESTANTE(ID_ESTANTE)
  ENABLE; 
 ALTER TABLE A_CANTIDAD_EN_ESTANTES
    ADD CONSTRAINT CK_CA_CANTIDAD_EN_ESTANTES
    CHECK (CANTIDAD_ACTUAL > 0)
  ENABLE;
  ALTER TABLE A_CANTIDAD_EN_ESTANTES
    ADD CONSTRAINT CK_CM_CANTIDAD_EN_ESTANTES
    CHECK (CANTIDAD_MINIMA > 0)
  ENABLE;
  
 -- Creación de la tabla FACTURAS y sus especificaciones 
 CREATE
    TABLE A_FACTURAS
    (
        DIRECCION_SUCURSAL VARCHAR(255),
        CIUDAD VARCHAR(255),
        ID_FACTURA NUMBER,
        CONSTRAINT A_FACTURAS_PK PRIMARY KEY(DIRECCION_SUCURSAL, CIUDAD, ID_FACTURA)
    );
 ALTER TABLE A_FACTURAS
    ADD CONSTRAINT FK_S_FACTURAS
    FOREIGN KEY (DIRECCION_SUCURSAL, CIUDAD)
    REFERENCES A_SUCURSAL (DIRECCION_SUCURSAL, CIUDAD)
 ENABLE;
 ALTER TABLE A_FACTURAS
    ADD CONSTRAINT FK_IF_FACTURAS
    FOREIGN KEY (ID_FACTURA)
    REFERENCES A_FACTURA (ID_FACTURA)
 ENABLE;
 
  -- Creación de la tabla ORDEN PEDIDO y especificación de sus restricciones
 CREATE
    TABLE A_ORDEN_PEDIDO
    (
        FECHA_ESPERADA_ENTREGA DATE NOT NULL,
        ESTADO VARCHAR(255) NOT NULL,
        FECHA_ENTREGA DATE,
        CALIFICACION_PEDIDO VARCHAR(255),
        NIT_PROVEEDOR NUMBER,
        ID_PEDIDO NUMBER,
        CIUDAD VARCHAR (255),
        DIRECCION_SUCURSAL VARCHAR(255),
        DIRECCION_BODEGA VARCHAR(255),
        CONSTRAINT A_ORDEN_PEDIDO_PK PRIMARY KEY (ID_PEDIDO)
    );
 ALTER TABLE A_ORDEN_PEDIDO
    ADD CONSTRAINT FK_NP_ORDEN_PEDIDO
    FOREIGN KEY (NIT_PROVEEDOR)
    REFERENCES A_PROVEEDOR (NIT_PROVEEDOR)
 ENABLE;
 ALTER TABLE A_ORDEN_PEDIDO
    ADD CONSTRAINT FK_B_ORDEN_PEDIDO
    FOREIGN KEY (CIUDAD, DIRECCION_SUCURSAL, DIRECCION_BODEGA)
    REFERENCES A_BODEGA (CIUDAD, DIRECCION_SUCURSAL, DIRECCION_BODEGA)
 ENABLE;
 ALTER TABLE A_ORDEN_PEDIDO
    ADD CONSTRAINT CK_E_ORDEN_PEDIDO
    CHECK (ESTADO IN('Recibido','En espera','Cancelado'))
 ENABLE;
 
 -- Creación de la tabla PRODUCTO CATEGORÍA y especificación de sus restricciones.
 CREATE
    TABLE A_PRODUCTO_CATEGORIA
    (
        CODIGO_BARRAS VARCHAR(255),
        CATEGORIA VARCHAR(255),
        CONSTRAINT A_PRODUCTO_cATEGORIA_PK PRIMARY KEY(CODIGO_BARRAS, CATEGORIA)
    );
 ALTER TABLE A_PRODUCTO_CATEGORIA
    ADD CONSTRAINT FK_CD_PRODUCTO_CATEGORIA
    FOREIGN KEY (CODIGO_BARRAS)
    REFERENCES A_PRODUCTO(COD_BARRAS)
 ENABLE;
 ALTER TABLE A_PRODUCTO_CATEGORIA
    ADD CONSTRAINT FK_C_PRODUCTO_CATEGORIA
    FOREIGN KEY (CATEGORIA)
    REFERENCES A_CATEGORIA(NOMBRE_CATEGORIA)
 ENABLE;
 
 -- Creación de la tabla PRODUCTOS OFRECIDOS y especificación de sus restricciones
 CREATE
    TABLE A_PRODUCTOS_OFRECIDOS
    (
        DIRECCION_SUCURSAL VARCHAR(255),
        CIUDAD VARCHAR(255),
        CODIGO_BARRAS VARCHAR(255),
        NIVEL_REORDEN NUMBER,
        CONSTRAINT A_PRODUCTOS_OFRECIDOS_PK PRIMARY KEY(DIRECCION_SUCURSAL, CIUDAD, CODIGO_BARRAS)
    );
  ALTER TABLE A_PRODUCTOS_OFRECIDOS
    ADD CONSTRAINT FK_S_PRODUCTOS_OFRECIDOS
    FOREIGN KEY (DIRECCION_SUCURSAL, CIUDAD)
    REFERENCES A_SUCURSAL(DIRECCION_SUCURSAL, CIUDAD)
 ENABLE;
 ALTER TABLE A_PRODUCTOS_OFRECIDOS
    ADD CONSTRAINT FK_CD_PRODUCTOS_OFRECIDOS
    FOREIGN KEY (CODIGO_BARRAS)
    REFERENCES A_PRODUCTO(COD_BARRAS)
 ENABLE;
 ALTER TABLE A_PRODUCTOS_OFRECIDOS
    ADD CONSTRAINT CK_NR_PRODUCTOS_OFRECIDOS
    CHECK (NIVEL_REORDEN > 0)
 ENABLE;
COMMIT;